### ISSUE TITLE
Need Volume Support

### ISSUE THREAD

**Issue by issackelly** [cloudenvy/cloudenvy#99]
Suggested Config

```
volumes:
    <name>:
         size: [human readable size, or just (int)<gigs>]
         mount_point: /foo/bar
         fs: ext3
```
